
const actions = {
  LOGIN: 'LOGIN',
  APP_CONTACTS: 'APP_CONTACTS',
  USER_CONTACTS: 'USER_CONTACTS',
  USER_MESSAGES: 'USER_MESSAGES',
  UPDATE_USER_MESSAGES: 'UPDATE_USER_MESSAGES',
  ACTIVE_CONTACT: 'ACTIVE_CONTACT',
};

export default actions;
